pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  region: 'southcentralus'
  buildId: $(Build.BuildNumber)
  buildIdHyphen: $[replace(variables['Build.BuildNumber'],'.','-')]
  resourcesId: res-$(buildId)
  resourceGroup: RG-$(resourcesId)
  appServicePlan: SvcPlan-$(resourcesId)
  UriAppPocRandD2: https://$[replace(variables['Build.BuildNumber'],'.','-')].azurewebsites.net
  UriAppPocRandD: $[format('https://AppSvc-{0}.azurewebsites.net', replace(variables['Build.BuildNumber'],'.','-'))]

steps:
- script: echo $(UriAppPocRandD)
- bash: echo $(UriAppPocRandD)

