variables:
  buildId: $(Build.BuildNumber)
  host: randapp.azurewebsites.net

jobs:
- job: jmeter
  pool:
    vmImage: ubuntu-latest
  displayName: Run JMeter tests
  steps:
    - script: echo "======== parametros $PWD jmeterpocrandd.jmx $(host) $(buildId)"
      displayName: "Mensaje"
  # - task: Bash@3
  #   displayName: Execute JMeter tests
  #   inputs:
  #     targetType: filePath
  #     filePath: 'jmeter/test.sh'
  #     arguments: '$PWD jmeterpocrandd.jmx $(host) $(buildId)'
  #     workingDirectory: jmeter
  #     failOnStderr: false
  # - task: PublishPipelineArtifact@1
  #   displayName: Publish JMeter Report
  #   inputs:
  #     targetPath: jmeter/report
  #     artifact: jmeter

