pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  region: 'southcentralus'
  buildId: $(Build.BuildNumber)
  resourcesId: res-$(buildId)
  resourceGroup: RG-$(resourcesId)
  appServicePlan: SvcPlan-$(resourcesId)
  appService: AppSvc-$(appServicePlan)

steps:
- script: echo "Referencia1 $[replace($(appService),'.','-')]"
- bash: echo "Referencia2 $(appService)"

