pool:
  vmImage: 'ubuntu-latest'

variables:
  build: $(Build.BuildNumber)

steps:
- script: |
    sudo export IDBUILD=$(build)
    sudo export ID="${IDBUILD/./-}"
    sudo echo "Aqui si funciona $ID"
- script: sudo echo "Aqui ya no funciona $ID"
