pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  region: 'southcentralus'
  buildId: $(Build.BuildNumber)
  resourcesId: res-$(buildId)
  resourceGroup: RG-$(resourcesId)
  appServicePlan: SvcPlan-$(resourcesId)
  appService: AppSvc-$[replace(variables['Build.BuildNumber'],'.','-')]

steps:
- script: echo "Referencia1 $(appService)"
- bash: echo "Referencia2 $(appService)"

