pool:
  vmImage: 'ubuntu-latest'

variables:
  build: $(Build.BuildNumber)
  otro: ${{replace('https://www.tinfoilsecurity.com/saml/consume','https://www.tinfoilsecurity.com','http://server')}}

steps:
- script: |
    export IDBUILD=$(build)
    export ID="${IDBUILD/./-}"
    $(mivar) = $ID
    echo "$(otro)"
- script: echo "Aqui ya no funciona $(mivar)"
