pool:
  vmImage: 'ubuntu-latest'

variables:
  build: $(Build.BuildNumber)
  build2: ${{replace(variables['Build.BuildNumber'],'.','-')}}

steps:
- script: echo "Referencia1 $(build2)"
- bash: echo "Referencia2 $(build2)"
