variables:
  buildId: $(Build.BuildNumber)
  host: randapp.azurewebsites.net

jobs:
- job: MyJob
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: echo '$(System.DefaultWorkingDirectory)'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'src/PocRandD.Test/PocRandD.Test.csproj'
      arguments: '--results-directory:"./resultados" --collect:"XPlat Code Coverage"'

    displayName: 'Unit_Tests'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: /home/vsts/work/_temp/**/coverage.cobertura.xml
      #pathToSources: # Optional
      #reportDirectory: # Optional
      #additionalCodeCoverageFiles: # Optional
      #failIfCoverageEmpty: false # Optional
  - script: find /home/vsts/work/_temp -name "coverage.cobertura.xml"
  # - task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
  #   displayName: ReportGenerator
  #   inputs:
  #     reports: '$(Build.SourcesDirectory)/TestResults/Coverage/coverage.cobertura.xml'
  #     targetdir: '$(Build.SourcesDirectory)/TestResults/Coverage'
  #     sourcedirs: '$(Build.SourcesDirectory)'
