variables:
  buildId: $(Build.BuildNumber)
  host: randapp.azurewebsites.net

jobs:
- job: MyJob
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'src/PocRandD.Test/PocRandD.Test.csproj'
      arguments: '--collect:"XPlat Code Coverage"'
    displayName: 'Unit_Tests'
  - script: ls -l

