variables:
  buildId: $(Build.BuildNumber)
  host: randapp.azurewebsites.net

jobs:
- job: jmeter
  pool:
    vmImage: ubuntu-latest
  displayName: Run JMeter tests
  steps:
  # - task: Bash@3
  #   displayName: Execute JMeter tests
  #   inputs:
  #     targetType: filePath
  #     filePath: 'jmeter/test.sh'
  #     arguments: '$PWD jmeterpocrandd.jmx $(host) $(buildId)'
  #     workingDirectory: jmeter
  #     failOnStderr: false
  # - task: Bash@3
  #   displayName: 'Esperar respuesta de App'
  #   inputs:
  #     targetType: filePath
  #     filePath: 'infra/waitForApp.sh'
  #     arguments: 'https://$(host)'
  #     workingDirectory: infra
  #     failOnStderr: false
  - task: AzureKeyVault@1
    inputs:
      azureSubscription: 'SuscripcionMaru'
      KeyVaultName: 'keyvaultpocdevops'
      SecretsFilter: 'SonarToken'
      RunAsPreJob: true
  - script: echo "el Secret es: $(SonarToken)"
