pool:
  vmImage: 'ubuntu-latest'

variables:
  build: $(Build.BuildNumber)
  build2: ${{replace($(Build.BuildNumber),'.','-')}}

steps:
- script: |
    export IDBUILD=$(build)
    export ID="${IDBUILD/./-}"
    $(mivar) = $ID
    echo "$(build2)"
- script: echo "Aqui ya no funciona $(build2)"
