pool:
  vmImage: 'ubuntu-latest'

variables:
  build: $(Build.BuildNumber)

steps:
- bash: |
    export IDBUILD=$(build)
    export ID="${IDBUILD/./-}"
    echo "Aqui si funciona $ID"
- script: echo "Aqui ya no funciona $ID"
