pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  region: 'southcentralus'
  buildId: $(Build.BuildNumber)
  resourcesId: res-$(buildId)
  resourceGroup: RG-$(resourcesId)
  appServicePlan: SvcPlan-$(resourcesId)
  buildIdHyphen: $[replace(variables['Build.BuildNumber'],'.','-')]

steps:
- script: echo "AppSvs-$(buildIdHyphen)"
- bash: echo "AppSvs-$(buildIdHyphen)"

