variables:
  buildId: $(Build.BuildNumber)
  host: randapp.azurewebsites.net

jobs:
- job: MyJob
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'src/PocRandD.Test/PocRandD.Test.csproj'
      arguments: '--collect:"XPlat Code Coverage"'
    displayName: 'Unit_Tests'
  - script: echo '$(Build.SourcesDirectory)'
  - script: ls -l -r
  # - task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
  #   displayName: ReportGenerator
  #   inputs:
  #     reports: '$(Build.SourcesDirectory)/TestResults/Coverage/coverage.cobertura.xml'
  #     targetdir: '$(Build.SourcesDirectory)/TestResults/Coverage'
  #     sourcedirs: '$(Build.SourcesDirectory)'
