variables:
  buildId: $(Build.BuildNumber)
  host: randapp.azurewebsites.net

jobs:
- job: jmeter
  pool:
    vmImage: ubuntu-latest
  displayName: MyJob
  steps:
  - script: echo 'Build.SourcesDirectory $(Build.SourcesDirectory)'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'src/PocRandD.Test/PocRandD.Test.csproj'
      arguments: '--configuration $(BuildConfiguration)  /p:CollectCoverage=true  /p:CoverletOutputFormat=cobertura   /p:CoverletOutput=$(Build.SourcesDirectory)\TestResults\Coverage\'
    displayName: 'Unit_Tests'
  - script: ls -l $(Build.SourcesDirectory)

