pool:
  vmImage: 'ubuntu-latest'

variables:
  build: $(Build.BuildNumber)


steps:
- script: |
    export IDBUILD=$(build)
    export ID="${IDBUILD/./-}"
    $MIVAR = $ID
    sudo echo "Aqui si funciona $MIVAR"
- script: sudo echo "Aqui ya no funciona $MIVAR"
